[tool.poetry]
name = "worker"
version = "0.1.0"
description = "Celery worker"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
celery = "^5.2.3"
redis = "^5.0.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
